### ISSUE TITLE
연간 회고 해보는 건 어떨까요?

### ISSUE THREAD

**Issue by NESOY** [WeareSoft/wwl#3]
2018년이 이제 이번 달을 포함해서 2달밖에 남지 않았는데..
2018년에 나는 무엇을 배웠으며 무엇이 부족했고 앞으로 개선하면 좋을 점을 블로그 or 글 형태로 작성해보는건 어떨까요?

**Comment by gmlwjd9405** [comment]
12월말까지 지속적으로 개인별 회고 내용 작성 후 연말에 공유 및 피드백 예정.
공개 여부와 공개 방법에 대해서는 개인에 따라 차이를 둠

**Comment by NESOY** [comment]
Nesoy
- https://nesoy.github.io/articles/2018-12/2018-retrospective
gmlwjd9405
- https://gmlwjd9405.github.io/2018/12/31/2018-retrospective.html
